COMMON_PATH := $(PARENT_DIR)/common

obj_common += \
	$(COMMON_PATH)/a4_conn.o\
	$(COMMON_PATH)/action.o\
	$(COMMON_PATH)/bcn.o\
	$(COMMON_PATH)/capi.o\
	$(COMMON_PATH)/cmm_cfg.o\
	$(COMMON_PATH)/cmm_cmd.o\
	$(COMMON_PATH)/cmm_data.o\
	$(COMMON_PATH)/cmm_info.o\
	$(COMMON_PATH)/cmm_info_element.o\
	$(COMMON_PATH)/cmm_mat.o\
	$(COMMON_PATH)/cmm_mat_iparp.o\
	$(COMMON_PATH)/cmm_mat_ipv6.o\
	$(COMMON_PATH)/cmm_mat_pppoe.o\
	$(COMMON_PATH)/cmm_radar.o\
	$(COMMON_PATH)/cmm_rvr_dbg.o\
	$(COMMON_PATH)/cmm_sanity.o\
	$(COMMON_PATH)/cmm_sync.o\
	$(COMMON_PATH)/dabs_qos.o\
	$(COMMON_PATH)/dump.o\
	$(COMMON_PATH)/fd.o\
	$(COMMON_PATH)/fp_qm.o\
	$(COMMON_PATH)/config_phy.o\
	$(COMMON_PATH)/log_time.o\
	$(COMMON_PATH)/misc_app.o\
	$(COMMON_PATH)/mld_link_mgr.o\
	$(COMMON_PATH)/mlme.o\
	$(COMMON_PATH)/multi_hif.o\
	$(COMMON_PATH)/op_class.o\
	$(COMMON_PATH)/qm.o\
	$(COMMON_PATH)/qos.o\
	$(COMMON_PATH)/routing_tab.o\
	$(COMMON_PATH)/rt_channel.o\
	$(COMMON_PATH)/rt_os_util.o\
	$(COMMON_PATH)/rtmp_init.o\
	$(COMMON_PATH)/rtmp_init_inf.o\
	$(COMMON_PATH)/rtmp_timer.o\
	$(COMMON_PATH)/safe_chn.o\
	$(COMMON_PATH)/scan.o\
	$(COMMON_PATH)/sniffer_prism.o\
	$(COMMON_PATH)/sniffer_radiotap.o\
	$(COMMON_PATH)/spectrum.o\
	$(COMMON_PATH)/sys_log.o\
	$(COMMON_PATH)/txs.o\
	$(COMMON_PATH)/wdev.o\
	$(COMMON_PATH)/wifi_sys_info.o\
	$(COMMON_PATH)/wifi_sys_notify.o\
	$(COMMON_PATH)/scan_util.o\
	$(COMMON_PATH)/token.o\
	$(COMMON_PATH)/cmm_tcprack.o\
	$(COMMON_PATH)/ba_action.o\
	$(COMMON_PATH)/vendor.o\
	$(COMMON_PATH)/client_wds.o\
	$(COMMON_PATH)/he_cfg.o\
	$(COMMON_PATH)/dbg_ctrl.o\
	$(COMMON_PATH)/multi_channel.o\
	$(COMMON_PATH)/cmm_rdm_mt.o\
	$(COMMON_PATH)/rt_led.o\
	$(COMMON_PATH)/bgnd_scan.o\
	$(COMMON_PATH)/scs.o\
	$(COMMON_PATH)/afc.o\
	$(COMMON_PATH)/tmr.o
