//[File]            : conn_mcu_excp_con.h
//[Revision time]   : Thu Dec  8 14:53:48 2022
//[Description]     : This file is auto generated by CODA
//[Copyright]       : Copyright (C) 2022 Mediatek Incorportion. All rights reserved.

#ifndef __CONN_MCU_EXCP_CON_REGS_H__
#define __CONN_MCU_EXCP_CON_REGS_H__

#include "hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif


//****************************************************************************
//
//                     CONN_MCU_EXCP_CON CR Definitions                     
//
//****************************************************************************

#define CONN_MCU_EXCP_CON_BASE                                 0x89050000
#define CONN_MCU_WA_EXCP_CON_BASE                              0x890d0000

#define CONN_MCU_EXCP_CON_HANG_DET_CTL_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0000) // 0000
#define CONN_MCU_EXCP_CON_HANG_CYC_THRE_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0004) // 0004
#define CONN_MCU_EXCP_CON_PC_CHK_BITMAP_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0008) // 0008
#define CONN_MCU_EXCP_CON_IGN_ADDR_CFG_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x000C) // 000C
#define CONN_MCU_EXCP_CON_IGN_ADDR_0_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0010) // 0010
#define CONN_MCU_EXCP_CON_IGN_ADDR_1_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0014) // 0014
#define CONN_MCU_EXCP_CON_IGN_ADDR_2_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0018) // 0018
#define CONN_MCU_EXCP_CON_IGN_ADDR_3_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x001C) // 001C
#define CONN_MCU_EXCP_CON_IGN_ADDR_4_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0020) // 0020
#define CONN_MCU_EXCP_CON_IGN_ADDR_5_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0024) // 0024
#define CONN_MCU_EXCP_CON_IGN_ADDR_6_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0028) // 0028
#define CONN_MCU_EXCP_CON_IGN_ADDR_7_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x002C) // 002C
#define CONN_MCU_EXCP_CON_RO_CHK_PC_ADDR                       (CONN_MCU_EXCP_CON_BASE + 0x0030) // 0030
#define CONN_MCU_EXCP_CON_RO_CYC_CNT_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0034) // 0034
#define CONN_MCU_EXCP_CON_PC_MON_CTL_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0038) // 0038
#define CONN_MCU_EXCP_CON_PC_MON_STS_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x003C) // 003C
#define CONN_MCU_EXCP_CON_MON_PC_CFG0_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0040) // 0040
#define CONN_MCU_EXCP_CON_MON_PC_CFG1_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0044) // 0044
#define CONN_MCU_EXCP_CON_MON_PC_CFG2_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0048) // 0048
#define CONN_MCU_EXCP_CON_MON_PC_CFG3_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x004C) // 004C
#define CONN_MCU_EXCP_CON_MON_PC_CFG4_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0050) // 0050
#define CONN_MCU_EXCP_CON_MON_PC_CFG5_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0054) // 0054
#define CONN_MCU_EXCP_CON_MON_PC_CFG6_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0058) // 0058
#define CONN_MCU_EXCP_CON_MON_PC_CFG7_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x005C) // 005C
#define CONN_MCU_EXCP_CON_MON_PC_CFG8_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0060) // 0060
#define CONN_MCU_EXCP_CON_MON_PC_CFG9_ADDR                     (CONN_MCU_EXCP_CON_BASE + 0x0064) // 0064
#define CONN_MCU_EXCP_CON_MON_PC_CFG10_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0068) // 0068
#define CONN_MCU_EXCP_CON_MON_PC_CFG11_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x006C) // 006C
#define CONN_MCU_EXCP_CON_MON_PC_CFG12_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0070) // 0070
#define CONN_MCU_EXCP_CON_MON_PC_CFG13_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0074) // 0074
#define CONN_MCU_EXCP_CON_MON_PC_CFG14_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0078) // 0078
#define CONN_MCU_EXCP_CON_MON_PC_CFG15_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x007C) // 007C
#define CONN_MCU_EXCP_CON_SW_DBG_CTL_ADDR                      (CONN_MCU_EXCP_CON_BASE + 0x0080) // 0080
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CMD_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0090) // 0090
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG0_ADDR                 (CONN_MCU_EXCP_CON_BASE + 0x0094) // 0094
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG1_ADDR                 (CONN_MCU_EXCP_CON_BASE + 0x0098) // 0098
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CTL_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x009C) // 009C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0100) // 0100
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_0_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0104) // 0104
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_1_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0108) // 0108
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_2_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x010C) // 010C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_3_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0110) // 0110
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_4_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0114) // 0114
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_5_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0118) // 0118
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_6_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x011C) // 011C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_7_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0120) // 0120
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_8_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0124) // 0124
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_9_ADDR                    (CONN_MCU_EXCP_CON_BASE + 0x0128) // 0128
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_10_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x012C) // 012C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_11_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0130) // 0130
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_12_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0134) // 0134
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_13_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0138) // 0138
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_14_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x013C) // 013C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_15_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0140) // 0140
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_16_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0144) // 0144
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_17_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0148) // 0148
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_18_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x014C) // 014C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_19_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0150) // 0150
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_20_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0154) // 0154
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_21_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0158) // 0158
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_22_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x015C) // 015C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_23_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0160) // 0160
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_24_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0164) // 0164
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_25_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0168) // 0168
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_26_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x016C) // 016C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_27_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0170) // 0170
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_28_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0174) // 0174
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_29_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0178) // 0178
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_30_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x017C) // 017C
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_31_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0180) // 0180
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_ADDR             (CONN_MCU_EXCP_CON_BASE + 0x01FC) // 01FC
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_ADDR                 (CONN_MCU_EXCP_CON_BASE + 0x0200) // 0200
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_0_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0204) // 0204
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_1_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0208) // 0208
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_2_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x020C) // 020C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_3_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0210) // 0210
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_4_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0214) // 0214
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_5_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0218) // 0218
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_6_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x021C) // 021C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_7_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0220) // 0220
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_8_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0224) // 0224
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_9_ADDR                   (CONN_MCU_EXCP_CON_BASE + 0x0228) // 0228
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_10_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x022C) // 022C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_11_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0230) // 0230
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_12_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0234) // 0234
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_13_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0238) // 0238
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_14_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x023C) // 023C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_15_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0240) // 0240
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_16_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0244) // 0244
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_17_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0248) // 0248
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_18_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x024C) // 024C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_19_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0250) // 0250
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_20_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0254) // 0254
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_21_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0258) // 0258
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_22_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x025C) // 025C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_23_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0260) // 0260
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_24_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0264) // 0264
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_25_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0268) // 0268
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_26_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x026C) // 026C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_27_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0270) // 0270
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_28_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0274) // 0274
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_29_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0278) // 0278
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_30_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x027C) // 027C
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_31_ADDR                  (CONN_MCU_EXCP_CON_BASE + 0x0280) // 0280
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_ADDR                 (CONN_MCU_EXCP_CON_BASE + 0x0300) // 0300
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_ADDR                (CONN_MCU_EXCP_CON_BASE + 0x0304) // 0304
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_ADDR            (CONN_MCU_EXCP_CON_BASE + 0x0308) // 0308
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_ADDR           (CONN_MCU_EXCP_CON_BASE + 0x030C) // 030C




/* =====================================================================================

  ---HANG_DET_CTL (0x890d0000 + 0x0000)---

    HANG_DET_EN[0]               - (RW) CPU hang detection enable
                                     1: enable
                                     0: disable
    RST_CYC_CNT[1]               - (RW) Reset hang cycle counter
                                     write 1 to reset, then write 0 to release reset
    RESERVED2[27..2]             - (RO) Reserved bits
    INT_EN[29..28]               - (RW) NMI Interrupt enable
                                     bit[28] for PC hang INT enable
                                     bit[29] for PC hit INT enable
                                     1: enable
                                     0: disable
    INT_STS[31..30]              - (W1C) INT status
                                     write 1 to clear
                                     bit[30] for INT_EN[28]
                                     bit[31] for INT_EN[29]
                                     1: INT pending
                                     0: INT not pending

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_INT_STS_ADDR            CONN_MCU_EXCP_CON_HANG_DET_CTL_ADDR
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_INT_STS_MASK            0xC0000000                // INT_STS[31..30]
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_INT_STS_SHFT            30
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_INT_EN_ADDR             CONN_MCU_EXCP_CON_HANG_DET_CTL_ADDR
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_INT_EN_MASK             0x30000000                // INT_EN[29..28]
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_INT_EN_SHFT             28
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_RST_CYC_CNT_ADDR        CONN_MCU_EXCP_CON_HANG_DET_CTL_ADDR
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_RST_CYC_CNT_MASK        0x00000002                // RST_CYC_CNT[1]
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_RST_CYC_CNT_SHFT        1
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_HANG_DET_EN_ADDR        CONN_MCU_EXCP_CON_HANG_DET_CTL_ADDR
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_HANG_DET_EN_MASK        0x00000001                // HANG_DET_EN[0]
#define CONN_MCU_EXCP_CON_HANG_DET_CTL_HANG_DET_EN_SHFT        0

/* =====================================================================================

  ---HANG_CYC_THRE (0x890d0000 + 0x0004)---

    HANG_CYC_THRE[31..0]         - (RW) Hang cycle threshold
                                     If checked PC remains the same for the specified cycle number, it is detected as CPU hang, and INT is issued if enabled.

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_HANG_CYC_THRE_HANG_CYC_THRE_ADDR     CONN_MCU_EXCP_CON_HANG_CYC_THRE_ADDR
#define CONN_MCU_EXCP_CON_HANG_CYC_THRE_HANG_CYC_THRE_MASK     0xFFFFFFFF                // HANG_CYC_THRE[31..0]
#define CONN_MCU_EXCP_CON_HANG_CYC_THRE_HANG_CYC_THRE_SHFT     0

/* =====================================================================================

  ---PC_CHK_BITMAP (0x890d0000 + 0x0008)---

    PC_CHK_BITMAP[31..0]         - (RW) Program Counter Check Bitmap
                                     Don't check LSB parts to mimic locality. When the check part of PC remains the same, it is thought that PC resides in a loop. 
                                     1: check
                                     0: don't check

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_PC_CHK_BITMAP_PC_CHK_BITMAP_ADDR     CONN_MCU_EXCP_CON_PC_CHK_BITMAP_ADDR
#define CONN_MCU_EXCP_CON_PC_CHK_BITMAP_PC_CHK_BITMAP_MASK     0xFFFFFFFF                // PC_CHK_BITMAP[31..0]
#define CONN_MCU_EXCP_CON_PC_CHK_BITMAP_PC_CHK_BITMAP_SHFT     0

/* =====================================================================================

  ---IGN_ADDR_CFG (0x890d0000 + 0x000C)---

    IGN_EN[7..0]                 - (RW) Ignore enable
                                     Bit N is enable bit for ingore address CR N
                                     1: ignore address CR N
                                     0: don't ignore address CR N
    RESERVED8[31..8]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_CFG_IGN_EN_ADDR             CONN_MCU_EXCP_CON_IGN_ADDR_CFG_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_CFG_IGN_EN_MASK             0x000000FF                // IGN_EN[7..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_CFG_IGN_EN_SHFT             0

/* =====================================================================================

  ---IGN_ADDR_0 (0x890d0000 + 0x0010)---

    IGN_ADDR_0[31..0]            - (RW) Ignore address 0

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_0_IGN_ADDR_0_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_0_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_0_IGN_ADDR_0_MASK           0xFFFFFFFF                // IGN_ADDR_0[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_0_IGN_ADDR_0_SHFT           0

/* =====================================================================================

  ---IGN_ADDR_1 (0x890d0000 + 0x0014)---

    IGN_ADDR_1[31..0]            - (RW) Ignore address 1

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_1_IGN_ADDR_1_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_1_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_1_IGN_ADDR_1_MASK           0xFFFFFFFF                // IGN_ADDR_1[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_1_IGN_ADDR_1_SHFT           0

/* =====================================================================================

  ---IGN_ADDR_2 (0x890d0000 + 0x0018)---

    IGN_ADDR_2[31..0]            - (RW) Ignore address 2

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_2_IGN_ADDR_2_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_2_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_2_IGN_ADDR_2_MASK           0xFFFFFFFF                // IGN_ADDR_2[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_2_IGN_ADDR_2_SHFT           0

/* =====================================================================================

  ---IGN_ADDR_3 (0x890d0000 + 0x001C)---

    IGN_ADDR_3[31..0]            - (RW) Ignore address 3

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_3_IGN_ADDR_3_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_3_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_3_IGN_ADDR_3_MASK           0xFFFFFFFF                // IGN_ADDR_3[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_3_IGN_ADDR_3_SHFT           0

/* =====================================================================================

  ---IGN_ADDR_4 (0x890d0000 + 0x0020)---

    IGN_ADDR_4[31..0]            - (RW) Ignore address 4

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_4_IGN_ADDR_4_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_4_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_4_IGN_ADDR_4_MASK           0xFFFFFFFF                // IGN_ADDR_4[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_4_IGN_ADDR_4_SHFT           0

/* =====================================================================================

  ---IGN_ADDR_5 (0x890d0000 + 0x0024)---

    IGN_ADDR_5[31..0]            - (RW) Ignore address 5

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_5_IGN_ADDR_5_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_5_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_5_IGN_ADDR_5_MASK           0xFFFFFFFF                // IGN_ADDR_5[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_5_IGN_ADDR_5_SHFT           0

/* =====================================================================================

  ---IGN_ADDR_6 (0x890d0000 + 0x0028)---

    IGN_ADDR_6[31..0]            - (RW) Ignore address 6

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_6_IGN_ADDR_6_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_6_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_6_IGN_ADDR_6_MASK           0xFFFFFFFF                // IGN_ADDR_6[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_6_IGN_ADDR_6_SHFT           0

/* =====================================================================================

  ---IGN_ADDR_7 (0x890d0000 + 0x002C)---

    IGN_ADDR_7[31..0]            - (RW) Ignore address 7

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_IGN_ADDR_7_IGN_ADDR_7_ADDR           CONN_MCU_EXCP_CON_IGN_ADDR_7_ADDR
#define CONN_MCU_EXCP_CON_IGN_ADDR_7_IGN_ADDR_7_MASK           0xFFFFFFFF                // IGN_ADDR_7[31..0]
#define CONN_MCU_EXCP_CON_IGN_ADDR_7_IGN_ADDR_7_SHFT           0

/* =====================================================================================

  ---RO_CHK_PC (0x890d0000 + 0x0030)---

    RO_CHK_PC[31..0]             - (RO) current checked PC

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_RO_CHK_PC_RO_CHK_PC_ADDR             CONN_MCU_EXCP_CON_RO_CHK_PC_ADDR
#define CONN_MCU_EXCP_CON_RO_CHK_PC_RO_CHK_PC_MASK             0xFFFFFFFF                // RO_CHK_PC[31..0]
#define CONN_MCU_EXCP_CON_RO_CHK_PC_RO_CHK_PC_SHFT             0

/* =====================================================================================

  ---RO_CYC_CNT (0x890d0000 + 0x0034)---

    RO_CYC_CNT[31..0]            - (RO) current cycle counter (of current cheked PC)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_RO_CYC_CNT_RO_CYC_CNT_ADDR           CONN_MCU_EXCP_CON_RO_CYC_CNT_ADDR
#define CONN_MCU_EXCP_CON_RO_CYC_CNT_RO_CYC_CNT_MASK           0xFFFFFFFF                // RO_CYC_CNT[31..0]
#define CONN_MCU_EXCP_CON_RO_CYC_CNT_RO_CYC_CNT_SHFT           0

/* =====================================================================================

  ---PC_MON_CTL (0x890d0000 + 0x0038)---

    PC_MON_EN[15..0]             - (RW) PC monitor enable
                                     bit[0] is corresponding to MON_PC_CFG0
                                     bit[1] is corresponding to MON_PC_CFG1, etc.
                                     1: enable
                                     0: disable
    RESERVED16[30..16]           - (RO) Reserved bits
    RST_PC_MON_STS[31]           - (RW) Reset PC monitor status
                                     write 1, and then write 0 to reset PC_MON_STS

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_PC_MON_CTL_RST_PC_MON_STS_ADDR       CONN_MCU_EXCP_CON_PC_MON_CTL_ADDR
#define CONN_MCU_EXCP_CON_PC_MON_CTL_RST_PC_MON_STS_MASK       0x80000000                // RST_PC_MON_STS[31]
#define CONN_MCU_EXCP_CON_PC_MON_CTL_RST_PC_MON_STS_SHFT       31
#define CONN_MCU_EXCP_CON_PC_MON_CTL_PC_MON_EN_ADDR            CONN_MCU_EXCP_CON_PC_MON_CTL_ADDR
#define CONN_MCU_EXCP_CON_PC_MON_CTL_PC_MON_EN_MASK            0x0000FFFF                // PC_MON_EN[15..0]
#define CONN_MCU_EXCP_CON_PC_MON_CTL_PC_MON_EN_SHFT            0

/* =====================================================================================

  ---PC_MON_STS (0x890d0000 + 0x003C)---

    RO_PC_MON_STS[15..0]         - (RO) Latched PC_MON_STS when INT is triggered
                                     If INT is enabled, for SW to find which monitor address is hit
                                     1: monitor enable, and corresponding PC was hit
                                     0: monitor disable, or corresponding PC was not hit
    RESERVED16[31..16]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_PC_MON_STS_RO_PC_MON_STS_ADDR        CONN_MCU_EXCP_CON_PC_MON_STS_ADDR
#define CONN_MCU_EXCP_CON_PC_MON_STS_RO_PC_MON_STS_MASK        0x0000FFFF                // RO_PC_MON_STS[15..0]
#define CONN_MCU_EXCP_CON_PC_MON_STS_RO_PC_MON_STS_SHFT        0

/* =====================================================================================

  ---MON_PC_CFG0 (0x890d0000 + 0x0040)---

    MON_ADDR_0[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG0_MON_ADDR_0_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG0_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG0_MON_ADDR_0_MASK          0xFFFFFFFF                // MON_ADDR_0[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG0_MON_ADDR_0_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG1 (0x890d0000 + 0x0044)---

    MON_ADDR_1[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG1_MON_ADDR_1_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG1_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG1_MON_ADDR_1_MASK          0xFFFFFFFF                // MON_ADDR_1[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG1_MON_ADDR_1_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG2 (0x890d0000 + 0x0048)---

    MON_ADDR_2[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG2_MON_ADDR_2_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG2_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG2_MON_ADDR_2_MASK          0xFFFFFFFF                // MON_ADDR_2[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG2_MON_ADDR_2_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG3 (0x890d0000 + 0x004C)---

    MON_ADDR_3[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG3_MON_ADDR_3_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG3_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG3_MON_ADDR_3_MASK          0xFFFFFFFF                // MON_ADDR_3[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG3_MON_ADDR_3_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG4 (0x890d0000 + 0x0050)---

    MON_ADDR_4[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG4_MON_ADDR_4_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG4_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG4_MON_ADDR_4_MASK          0xFFFFFFFF                // MON_ADDR_4[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG4_MON_ADDR_4_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG5 (0x890d0000 + 0x0054)---

    MON_ADDR_5[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG5_MON_ADDR_5_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG5_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG5_MON_ADDR_5_MASK          0xFFFFFFFF                // MON_ADDR_5[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG5_MON_ADDR_5_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG6 (0x890d0000 + 0x0058)---

    MON_ADDR_6[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG6_MON_ADDR_6_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG6_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG6_MON_ADDR_6_MASK          0xFFFFFFFF                // MON_ADDR_6[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG6_MON_ADDR_6_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG7 (0x890d0000 + 0x005C)---

    MON_ADDR_7[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG7_MON_ADDR_7_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG7_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG7_MON_ADDR_7_MASK          0xFFFFFFFF                // MON_ADDR_7[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG7_MON_ADDR_7_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG8 (0x890d0000 + 0x0060)---

    MON_ADDR_8[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG8_MON_ADDR_8_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG8_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG8_MON_ADDR_8_MASK          0xFFFFFFFF                // MON_ADDR_8[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG8_MON_ADDR_8_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG9 (0x890d0000 + 0x0064)---

    MON_ADDR_9[31..0]            - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG9_MON_ADDR_9_ADDR          CONN_MCU_EXCP_CON_MON_PC_CFG9_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG9_MON_ADDR_9_MASK          0xFFFFFFFF                // MON_ADDR_9[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG9_MON_ADDR_9_SHFT          0

/* =====================================================================================

  ---MON_PC_CFG10 (0x890d0000 + 0x0068)---

    MON_ADDR_10[31..0]           - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG10_MON_ADDR_10_ADDR        CONN_MCU_EXCP_CON_MON_PC_CFG10_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG10_MON_ADDR_10_MASK        0xFFFFFFFF                // MON_ADDR_10[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG10_MON_ADDR_10_SHFT        0

/* =====================================================================================

  ---MON_PC_CFG11 (0x890d0000 + 0x006C)---

    MON_ADDR_11[31..0]           - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG11_MON_ADDR_11_ADDR        CONN_MCU_EXCP_CON_MON_PC_CFG11_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG11_MON_ADDR_11_MASK        0xFFFFFFFF                // MON_ADDR_11[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG11_MON_ADDR_11_SHFT        0

/* =====================================================================================

  ---MON_PC_CFG12 (0x890d0000 + 0x0070)---

    MON_ADDR_12[31..0]           - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG12_MON_ADDR_12_ADDR        CONN_MCU_EXCP_CON_MON_PC_CFG12_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG12_MON_ADDR_12_MASK        0xFFFFFFFF                // MON_ADDR_12[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG12_MON_ADDR_12_SHFT        0

/* =====================================================================================

  ---MON_PC_CFG13 (0x890d0000 + 0x0074)---

    MON_ADDR_13[31..0]           - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG13_MON_ADDR_13_ADDR        CONN_MCU_EXCP_CON_MON_PC_CFG13_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG13_MON_ADDR_13_MASK        0xFFFFFFFF                // MON_ADDR_13[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG13_MON_ADDR_13_SHFT        0

/* =====================================================================================

  ---MON_PC_CFG14 (0x890d0000 + 0x0078)---

    MON_ADDR_14[31..0]           - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG14_MON_ADDR_14_ADDR        CONN_MCU_EXCP_CON_MON_PC_CFG14_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG14_MON_ADDR_14_MASK        0xFFFFFFFF                // MON_ADDR_14[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG14_MON_ADDR_14_SHFT        0

/* =====================================================================================

  ---MON_PC_CFG15 (0x890d0000 + 0x007C)---

    MON_ADDR_15[31..0]           - (RW) montior address

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MON_PC_CFG15_MON_ADDR_15_ADDR        CONN_MCU_EXCP_CON_MON_PC_CFG15_ADDR
#define CONN_MCU_EXCP_CON_MON_PC_CFG15_MON_ADDR_15_MASK        0xFFFFFFFF                // MON_ADDR_15[31..0]
#define CONN_MCU_EXCP_CON_MON_PC_CFG15_MON_ADDR_15_SHFT        0

/* =====================================================================================

  ---SW_DBG_CTL (0x890d0000 + 0x0080)---

    SW_DBG_CTL[31..0]            - (RW) SW debug index

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_SW_DBG_CTL_SW_DBG_CTL_ADDR           CONN_MCU_EXCP_CON_SW_DBG_CTL_ADDR
#define CONN_MCU_EXCP_CON_SW_DBG_CTL_SW_DBG_CTL_MASK           0xFFFFFFFF                // SW_DBG_CTL[31..0]
#define CONN_MCU_EXCP_CON_SW_DBG_CTL_SW_DBG_CTL_SHFT           0

/* =====================================================================================

  ---MCU_DBG_IF_CMD (0x890d0000 + 0x0090)---

    MCU_DBG_IF_CMD[31..0]        - (RW) MCU_DBG_IF_CMD

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CMD_MCU_DBG_IF_CMD_ADDR   CONN_MCU_EXCP_CON_MCU_DBG_IF_CMD_ADDR
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CMD_MCU_DBG_IF_CMD_MASK   0xFFFFFFFF                // MCU_DBG_IF_CMD[31..0]
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CMD_MCU_DBG_IF_CMD_SHFT   0

/* =====================================================================================

  ---MCU_DBG_IF_ARG0 (0x890d0000 + 0x0094)---

    MCU_DBG_IF_ARG0[31..0]       - (RW) MCU_DBG_IF_ARG0

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG0_MCU_DBG_IF_ARG0_ADDR CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG0_ADDR
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG0_MCU_DBG_IF_ARG0_MASK 0xFFFFFFFF                // MCU_DBG_IF_ARG0[31..0]
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG0_MCU_DBG_IF_ARG0_SHFT 0

/* =====================================================================================

  ---MCU_DBG_IF_ARG1 (0x890d0000 + 0x0098)---

    MCU_DBG_IF_ARG1[31..0]       - (RW) MCU_DBG_IF_ARG1

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG1_MCU_DBG_IF_ARG1_ADDR CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG1_ADDR
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG1_MCU_DBG_IF_ARG1_MASK 0xFFFFFFFF                // MCU_DBG_IF_ARG1[31..0]
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_ARG1_MCU_DBG_IF_ARG1_SHFT 0

/* =====================================================================================

  ---MCU_DBG_IF_CTL (0x890d0000 + 0x009C)---

    MCU_DBG_IF_SW_IRQ[0]         - (RW) MCU_DBG_IF_SW_IRQ
                                     1'b0: Not issue interrupt
                                     1'b1: Issue interrupt
    RESERVED1[31..1]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CTL_MCU_DBG_IF_SW_IRQ_ADDR CONN_MCU_EXCP_CON_MCU_DBG_IF_CTL_ADDR
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CTL_MCU_DBG_IF_SW_IRQ_MASK 0x00000001                // MCU_DBG_IF_SW_IRQ[0]
#define CONN_MCU_EXCP_CON_MCU_DBG_IF_CTL_MCU_DBG_IF_SW_IRQ_SHFT 0

/* =====================================================================================

  ---DBG_PC_LOG_CTL (0x890d0000 + 0x0100)---

    DBG_PC_LOG_EN[0]             - (RW) DBG_PC_LOG_EN
    DBG_PC_LOG_SEL_SRC[1]        - (RW) DBG_PC_LOG_SEL_SRC
                                     1'b0 : mux selection source from AP/HIF
                                     1'b1 : mux selection source from MCUSYS
    DBG_PC_LOG_SEL[7..2]         - (RW) DBG_PC_LOG_SEL
    DBG_PC_LOG_THRESHOLD[15..8]  - (RW) DBG_PC_LOG_THRESHOLD
    RO_DBG_PC_LOG_IDX_STATUS[20..16] - (RO) DBG_PC_LOG_IDX_STATUS
    RESERVED21[31..21]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_RO_DBG_PC_LOG_IDX_STATUS_ADDR CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_RO_DBG_PC_LOG_IDX_STATUS_MASK 0x001F0000                // RO_DBG_PC_LOG_IDX_STATUS[20..16]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_RO_DBG_PC_LOG_IDX_STATUS_SHFT 16
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_THRESHOLD_ADDR CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_THRESHOLD_MASK 0x0000FF00                // DBG_PC_LOG_THRESHOLD[15..8]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_THRESHOLD_SHFT 8
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_SEL_ADDR   CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_SEL_MASK   0x000000FC                // DBG_PC_LOG_SEL[7..2]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_SEL_SHFT   2
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_SEL_SRC_ADDR CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_SEL_SRC_MASK 0x00000002                // DBG_PC_LOG_SEL_SRC[1]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_SEL_SRC_SHFT 1
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_EN_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_EN_MASK    0x00000001                // DBG_PC_LOG_EN[0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_CTL_DBG_PC_LOG_EN_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_0 (0x890d0000 + 0x0104)---

    RO_DBG_PC_LOG_0[31..0]       - (RO) DBG_PC_LOG_0 (source pc 1)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_0_RO_DBG_PC_LOG_0_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_0_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_0_RO_DBG_PC_LOG_0_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_0[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_0_RO_DBG_PC_LOG_0_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_1 (0x890d0000 + 0x0108)---

    RO_DBG_PC_LOG_1[31..0]       - (RO) DBG_PC_LOG_1 (destination pc 1)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_1_RO_DBG_PC_LOG_1_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_1_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_1_RO_DBG_PC_LOG_1_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_1[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_1_RO_DBG_PC_LOG_1_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_2 (0x890d0000 + 0x010C)---

    RO_DBG_PC_LOG_2[31..0]       - (RO) DBG_PC_LOG_2 (source pc 2)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_2_RO_DBG_PC_LOG_2_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_2_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_2_RO_DBG_PC_LOG_2_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_2[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_2_RO_DBG_PC_LOG_2_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_3 (0x890d0000 + 0x0110)---

    RO_DBG_PC_LOG_3[31..0]       - (RO) DBG_PC_LOG_3 (destination pc 2)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_3_RO_DBG_PC_LOG_3_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_3_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_3_RO_DBG_PC_LOG_3_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_3[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_3_RO_DBG_PC_LOG_3_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_4 (0x890d0000 + 0x0114)---

    RO_DBG_PC_LOG_4[31..0]       - (RO) DBG_PC_LOG_4 (source pc 3)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_4_RO_DBG_PC_LOG_4_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_4_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_4_RO_DBG_PC_LOG_4_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_4[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_4_RO_DBG_PC_LOG_4_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_5 (0x890d0000 + 0x0118)---

    RO_DBG_PC_LOG_5[31..0]       - (RO) DBG_PC_LOG_5 (destination pc 3)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_5_RO_DBG_PC_LOG_5_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_5_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_5_RO_DBG_PC_LOG_5_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_5[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_5_RO_DBG_PC_LOG_5_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_6 (0x890d0000 + 0x011C)---

    RO_DBG_PC_LOG_6[31..0]       - (RO) DBG_PC_LOG_6 (source pc 4)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_6_RO_DBG_PC_LOG_6_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_6_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_6_RO_DBG_PC_LOG_6_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_6[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_6_RO_DBG_PC_LOG_6_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_7 (0x890d0000 + 0x0120)---

    RO_DBG_PC_LOG_7[31..0]       - (RO) DBG_PC_LOG_7 (destination pc 4)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_7_RO_DBG_PC_LOG_7_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_7_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_7_RO_DBG_PC_LOG_7_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_7[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_7_RO_DBG_PC_LOG_7_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_8 (0x890d0000 + 0x0124)---

    RO_DBG_PC_LOG_8[31..0]       - (RO) DBG_PC_LOG_8 (source pc 5)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_8_RO_DBG_PC_LOG_8_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_8_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_8_RO_DBG_PC_LOG_8_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_8[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_8_RO_DBG_PC_LOG_8_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_9 (0x890d0000 + 0x0128)---

    RO_DBG_PC_LOG_9[31..0]       - (RO) DBG_PC_LOG_9  (destination pc 5)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_9_RO_DBG_PC_LOG_9_ADDR    CONN_MCU_EXCP_CON_DBG_PC_LOG_9_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_9_RO_DBG_PC_LOG_9_MASK    0xFFFFFFFF                // RO_DBG_PC_LOG_9[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_9_RO_DBG_PC_LOG_9_SHFT    0

/* =====================================================================================

  ---DBG_PC_LOG_10 (0x890d0000 + 0x012C)---

    RO_DBG_PC_LOG_10[31..0]      - (RO) DBG_PC_LOG_10 (source pc 6)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_10_RO_DBG_PC_LOG_10_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_10_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_10_RO_DBG_PC_LOG_10_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_10[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_10_RO_DBG_PC_LOG_10_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_11 (0x890d0000 + 0x0130)---

    RO_DBG_PC_LOG_11[31..0]      - (RO) DBG_PC_LOG_11  (destination pc 6)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_11_RO_DBG_PC_LOG_11_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_11_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_11_RO_DBG_PC_LOG_11_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_11[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_11_RO_DBG_PC_LOG_11_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_12 (0x890d0000 + 0x0134)---

    RO_DBG_PC_LOG_12[31..0]      - (RO) DBG_PC_LOG_12 (source pc 7)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_12_RO_DBG_PC_LOG_12_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_12_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_12_RO_DBG_PC_LOG_12_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_12[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_12_RO_DBG_PC_LOG_12_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_13 (0x890d0000 + 0x0138)---

    RO_DBG_PC_LOG_13[31..0]      - (RO) DBG_PC_LOG_13  (destination pc 7)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_13_RO_DBG_PC_LOG_13_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_13_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_13_RO_DBG_PC_LOG_13_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_13[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_13_RO_DBG_PC_LOG_13_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_14 (0x890d0000 + 0x013C)---

    RO_DBG_PC_LOG_14[31..0]      - (RO) DBG_PC_LOG_14 (source pc 8)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_14_RO_DBG_PC_LOG_14_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_14_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_14_RO_DBG_PC_LOG_14_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_14[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_14_RO_DBG_PC_LOG_14_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_15 (0x890d0000 + 0x0140)---

    RO_DBG_PC_LOG_15[31..0]      - (RO) DBG_PC_LOG_15  (destination pc 8)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_15_RO_DBG_PC_LOG_15_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_15_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_15_RO_DBG_PC_LOG_15_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_15[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_15_RO_DBG_PC_LOG_15_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_16 (0x890d0000 + 0x0144)---

    RO_DBG_PC_LOG_16[31..0]      - (RO) DBG_PC_LOG_16 (source pc 9)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_16_RO_DBG_PC_LOG_16_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_16_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_16_RO_DBG_PC_LOG_16_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_16[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_16_RO_DBG_PC_LOG_16_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_17 (0x890d0000 + 0x0148)---

    RO_DBG_PC_LOG_17[31..0]      - (RO) DBG_PC_LOG_17  (destination pc 9)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_17_RO_DBG_PC_LOG_17_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_17_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_17_RO_DBG_PC_LOG_17_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_17[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_17_RO_DBG_PC_LOG_17_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_18 (0x890d0000 + 0x014C)---

    RO_DBG_PC_LOG_18[31..0]      - (RO) DBG_PC_LOG_18 (source pc 10)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_18_RO_DBG_PC_LOG_18_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_18_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_18_RO_DBG_PC_LOG_18_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_18[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_18_RO_DBG_PC_LOG_18_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_19 (0x890d0000 + 0x0150)---

    RO_DBG_PC_LOG_19[31..0]      - (RO) DBG_PC_LOG_19  (destination pc 10)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_19_RO_DBG_PC_LOG_19_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_19_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_19_RO_DBG_PC_LOG_19_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_19[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_19_RO_DBG_PC_LOG_19_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_20 (0x890d0000 + 0x0154)---

    RO_DBG_PC_LOG_20[31..0]      - (RO) DBG_PC_LOG_20 (source pc 11)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_20_RO_DBG_PC_LOG_20_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_20_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_20_RO_DBG_PC_LOG_20_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_20[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_20_RO_DBG_PC_LOG_20_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_21 (0x890d0000 + 0x0158)---

    RO_DBG_PC_LOG_21[31..0]      - (RO) DBG_PC_LOG_21  (destination pc 11)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_21_RO_DBG_PC_LOG_21_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_21_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_21_RO_DBG_PC_LOG_21_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_21[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_21_RO_DBG_PC_LOG_21_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_22 (0x890d0000 + 0x015C)---

    RO_DBG_PC_LOG_22[31..0]      - (RO) DBG_PC_LOG_22 (source pc 12)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_22_RO_DBG_PC_LOG_22_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_22_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_22_RO_DBG_PC_LOG_22_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_22[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_22_RO_DBG_PC_LOG_22_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_23 (0x890d0000 + 0x0160)---

    RO_DBG_PC_LOG_23[31..0]      - (RO) DBG_PC_LOG_23  (destination pc 12)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_23_RO_DBG_PC_LOG_23_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_23_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_23_RO_DBG_PC_LOG_23_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_23[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_23_RO_DBG_PC_LOG_23_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_24 (0x890d0000 + 0x0164)---

    RO_DBG_PC_LOG_24[31..0]      - (RO) DBG_PC_LOG_24 (source pc 13)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_24_RO_DBG_PC_LOG_24_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_24_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_24_RO_DBG_PC_LOG_24_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_24[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_24_RO_DBG_PC_LOG_24_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_25 (0x890d0000 + 0x0168)---

    RO_DBG_PC_LOG_25[31..0]      - (RO) DBG_PC_LOG_25  (destination pc 13)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_25_RO_DBG_PC_LOG_25_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_25_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_25_RO_DBG_PC_LOG_25_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_25[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_25_RO_DBG_PC_LOG_25_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_26 (0x890d0000 + 0x016C)---

    RO_DBG_PC_LOG_26[31..0]      - (RO) DBG_PC_LOG_26 (source pc 14)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_26_RO_DBG_PC_LOG_26_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_26_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_26_RO_DBG_PC_LOG_26_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_26[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_26_RO_DBG_PC_LOG_26_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_27 (0x890d0000 + 0x0170)---

    RO_DBG_PC_LOG_27[31..0]      - (RO) DBG_PC_LOG_27  (destination pc 14)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_27_RO_DBG_PC_LOG_27_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_27_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_27_RO_DBG_PC_LOG_27_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_27[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_27_RO_DBG_PC_LOG_27_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_28 (0x890d0000 + 0x0174)---

    RO_DBG_PC_LOG_28[31..0]      - (RO) DBG_PC_LOG_28 (source pc 15)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_28_RO_DBG_PC_LOG_28_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_28_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_28_RO_DBG_PC_LOG_28_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_28[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_28_RO_DBG_PC_LOG_28_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_29 (0x890d0000 + 0x0178)---

    RO_DBG_PC_LOG_29[31..0]      - (RO) DBG_PC_LOG_29  (destination pc 15)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_29_RO_DBG_PC_LOG_29_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_29_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_29_RO_DBG_PC_LOG_29_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_29[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_29_RO_DBG_PC_LOG_29_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_30 (0x890d0000 + 0x017C)---

    RO_DBG_PC_LOG_30[31..0]      - (RO) DBG_PC_LOG_30 (source pc 16)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_30_RO_DBG_PC_LOG_30_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_30_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_30_RO_DBG_PC_LOG_30_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_30[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_30_RO_DBG_PC_LOG_30_SHFT  0

/* =====================================================================================

  ---DBG_PC_LOG_31 (0x890d0000 + 0x0180)---

    RO_DBG_PC_LOG_31[31..0]      - (RO) DBG_PC_LOG_31  (destination pc 16)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_31_RO_DBG_PC_LOG_31_ADDR  CONN_MCU_EXCP_CON_DBG_PC_LOG_31_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_31_RO_DBG_PC_LOG_31_MASK  0xFFFFFFFF                // RO_DBG_PC_LOG_31[31..0]
#define CONN_MCU_EXCP_CON_DBG_PC_LOG_31_RO_DBG_PC_LOG_31_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_CTL_EXT (0x890d0000 + 0x01FC)---

    DBG_GPR_SEL_EXT[5..0]        - (RW) DBG_GPR_SEL_EXT
    DBG_GPR_SEL_EN[6]            - (RW) DBG_GPR_CSR_SEL
                                     1: GPR
                                     0: CSR
    RESERVED7[31..7]             - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_DBG_GPR_SEL_EN_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_DBG_GPR_SEL_EN_MASK 0x00000040                // DBG_GPR_SEL_EN[6]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_DBG_GPR_SEL_EN_SHFT 6
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_DBG_GPR_SEL_EXT_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_DBG_GPR_SEL_EXT_MASK 0x0000003F                // DBG_GPR_SEL_EXT[5..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_EXT_DBG_GPR_SEL_EXT_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_CTL (0x890d0000 + 0x0200)---

    DBG_GPR_LOG_EN[0]            - (RW) DBG_GPR_LOG_EN
    DBG_GPR_LOG_SEL_SRC[1]       - (RW) DBG_GPR_LOG_SEL_SRC
                                     1'b0 : mux selection source from AP/HIF
                                     1'b1 : mux selection source from MCUSYS
    DBG_GPR_LOG_SEL[7..2]        - (RW) DBG_GPR_LOG_SEL
    DBG_GPR_LOG_THRESHOLD[15..8] - (RW) DBG_GPR_LOG_THRESHOLD
    RO_DBG_GPR_LOG_IDX_STATUS[20..16] - (RO) DBG_GPR_LOG_IDX_STATUS
    DBG_GPR_SEL[26..21]          - (RW) DBG_GPR_SEL
                                     6'd1: ra
                                     6'd2: sp
                                     6'd3: gp
                                     6'd4: tp
                                     6'd5~6'd7: t0~t2
                                     6'd8~6'd9: s0~s1
                                     6'd10~6'd17 : a0~a7
                                     6'd18~6'd27 : s2~s11
                                     6'd28~6'd31 : t3~t6
    RESERVED27[31..27]           - (RO) Reserved bits

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_SEL_ADDR     CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_SEL_MASK     0x07E00000                // DBG_GPR_SEL[26..21]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_SEL_SHFT     21
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_RO_DBG_GPR_LOG_IDX_STATUS_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_RO_DBG_GPR_LOG_IDX_STATUS_MASK 0x001F0000                // RO_DBG_GPR_LOG_IDX_STATUS[20..16]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_RO_DBG_GPR_LOG_IDX_STATUS_SHFT 16
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_THRESHOLD_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_THRESHOLD_MASK 0x0000FF00                // DBG_GPR_LOG_THRESHOLD[15..8]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_THRESHOLD_SHFT 8
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_SEL_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_SEL_MASK 0x000000FC                // DBG_GPR_LOG_SEL[7..2]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_SEL_SHFT 2
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_SEL_SRC_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_SEL_SRC_MASK 0x00000002                // DBG_GPR_LOG_SEL_SRC[1]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_SEL_SRC_SHFT 1
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_EN_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_EN_MASK  0x00000001                // DBG_GPR_LOG_EN[0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_CTL_DBG_GPR_LOG_EN_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_0 (0x890d0000 + 0x0204)---

    RO_DBG_GPR_LOG_0[31..0]      - (RO) DBG_GPR_LOG_0 (source gpr 1)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_0_RO_DBG_GPR_LOG_0_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_0_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_0_RO_DBG_GPR_LOG_0_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_0[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_0_RO_DBG_GPR_LOG_0_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_1 (0x890d0000 + 0x0208)---

    RO_DBG_GPR_LOG_1[31..0]      - (RO) DBG_GPR_LOG_1 (destination gpr 1)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_1_RO_DBG_GPR_LOG_1_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_1_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_1_RO_DBG_GPR_LOG_1_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_1[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_1_RO_DBG_GPR_LOG_1_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_2 (0x890d0000 + 0x020C)---

    RO_DBG_GPR_LOG_2[31..0]      - (RO) DBG_GPR_LOG_2 (source gpr 2)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_2_RO_DBG_GPR_LOG_2_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_2_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_2_RO_DBG_GPR_LOG_2_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_2[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_2_RO_DBG_GPR_LOG_2_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_3 (0x890d0000 + 0x0210)---

    RO_DBG_GPR_LOG_3[31..0]      - (RO) DBG_GPR_LOG_3 (destination gpr 2)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_3_RO_DBG_GPR_LOG_3_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_3_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_3_RO_DBG_GPR_LOG_3_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_3[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_3_RO_DBG_GPR_LOG_3_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_4 (0x890d0000 + 0x0214)---

    RO_DBG_GPR_LOG_4[31..0]      - (RO) DBG_GPR_LOG_4 (source gpr 3)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_4_RO_DBG_GPR_LOG_4_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_4_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_4_RO_DBG_GPR_LOG_4_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_4[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_4_RO_DBG_GPR_LOG_4_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_5 (0x890d0000 + 0x0218)---

    RO_DBG_GPR_LOG_5[31..0]      - (RO) DBG_GPR_LOG_5 (destination gpr 3)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_5_RO_DBG_GPR_LOG_5_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_5_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_5_RO_DBG_GPR_LOG_5_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_5[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_5_RO_DBG_GPR_LOG_5_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_6 (0x890d0000 + 0x021C)---

    RO_DBG_GPR_LOG_6[31..0]      - (RO) DBG_GPR_LOG_6 (source gpr 4)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_6_RO_DBG_GPR_LOG_6_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_6_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_6_RO_DBG_GPR_LOG_6_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_6[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_6_RO_DBG_GPR_LOG_6_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_7 (0x890d0000 + 0x0220)---

    RO_DBG_GPR_LOG_7[31..0]      - (RO) DBG_GPR_LOG_7 (destination gpr 4)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_7_RO_DBG_GPR_LOG_7_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_7_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_7_RO_DBG_GPR_LOG_7_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_7[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_7_RO_DBG_GPR_LOG_7_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_8 (0x890d0000 + 0x0224)---

    RO_DBG_GPR_LOG_8[31..0]      - (RO) DBG_GPR_LOG_8 (source gpr 5)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_8_RO_DBG_GPR_LOG_8_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_8_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_8_RO_DBG_GPR_LOG_8_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_8[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_8_RO_DBG_GPR_LOG_8_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_9 (0x890d0000 + 0x0228)---

    RO_DBG_GPR_LOG_9[31..0]      - (RO) DBG_GPR_LOG_9  (destination gpr 5)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_9_RO_DBG_GPR_LOG_9_ADDR  CONN_MCU_EXCP_CON_DBG_GPR_LOG_9_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_9_RO_DBG_GPR_LOG_9_MASK  0xFFFFFFFF                // RO_DBG_GPR_LOG_9[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_9_RO_DBG_GPR_LOG_9_SHFT  0

/* =====================================================================================

  ---DBG_GPR_LOG_10 (0x890d0000 + 0x022C)---

    RO_DBG_GPR_LOG_10[31..0]     - (RO) DBG_GPR_LOG_10 (source gpr 6)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_10_RO_DBG_GPR_LOG_10_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_10_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_10_RO_DBG_GPR_LOG_10_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_10[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_10_RO_DBG_GPR_LOG_10_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_11 (0x890d0000 + 0x0230)---

    RO_DBG_GPR_LOG_11[31..0]     - (RO) DBG_GPR_LOG_11  (destination gpr 6)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_11_RO_DBG_GPR_LOG_11_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_11_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_11_RO_DBG_GPR_LOG_11_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_11[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_11_RO_DBG_GPR_LOG_11_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_12 (0x890d0000 + 0x0234)---

    RO_DBG_GPR_LOG_12[31..0]     - (RO) DBG_GPR_LOG_12 (source gpr 7)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_12_RO_DBG_GPR_LOG_12_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_12_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_12_RO_DBG_GPR_LOG_12_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_12[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_12_RO_DBG_GPR_LOG_12_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_13 (0x890d0000 + 0x0238)---

    RO_DBG_GPR_LOG_13[31..0]     - (RO) DBG_GPR_LOG_13  (destination gpr 7)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_13_RO_DBG_GPR_LOG_13_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_13_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_13_RO_DBG_GPR_LOG_13_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_13[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_13_RO_DBG_GPR_LOG_13_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_14 (0x890d0000 + 0x023C)---

    RO_DBG_GPR_LOG_14[31..0]     - (RO) DBG_GPR_LOG_14 (source gpr 8)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_14_RO_DBG_GPR_LOG_14_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_14_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_14_RO_DBG_GPR_LOG_14_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_14[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_14_RO_DBG_GPR_LOG_14_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_15 (0x890d0000 + 0x0240)---

    RO_DBG_GPR_LOG_15[31..0]     - (RO) DBG_GPR_LOG_15  (destination gpr 8)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_15_RO_DBG_GPR_LOG_15_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_15_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_15_RO_DBG_GPR_LOG_15_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_15[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_15_RO_DBG_GPR_LOG_15_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_16 (0x890d0000 + 0x0244)---

    RO_DBG_GPR_LOG_16[31..0]     - (RO) DBG_GPR_LOG_16 (source gpr 9)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_16_RO_DBG_GPR_LOG_16_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_16_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_16_RO_DBG_GPR_LOG_16_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_16[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_16_RO_DBG_GPR_LOG_16_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_17 (0x890d0000 + 0x0248)---

    RO_DBG_GPR_LOG_17[31..0]     - (RO) DBG_GPR_LOG_17  (destination gpr 9)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_17_RO_DBG_GPR_LOG_17_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_17_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_17_RO_DBG_GPR_LOG_17_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_17[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_17_RO_DBG_GPR_LOG_17_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_18 (0x890d0000 + 0x024C)---

    RO_DBG_GPR_LOG_18[31..0]     - (RO) DBG_GPR_LOG_18 (source gpr 10)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_18_RO_DBG_GPR_LOG_18_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_18_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_18_RO_DBG_GPR_LOG_18_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_18[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_18_RO_DBG_GPR_LOG_18_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_19 (0x890d0000 + 0x0250)---

    RO_DBG_GPR_LOG_19[31..0]     - (RO) DBG_GPR_LOG_19  (destination gpr 10)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_19_RO_DBG_GPR_LOG_19_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_19_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_19_RO_DBG_GPR_LOG_19_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_19[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_19_RO_DBG_GPR_LOG_19_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_20 (0x890d0000 + 0x0254)---

    RO_DBG_GPR_LOG_20[31..0]     - (RO) DBG_GPR_LOG_20 (source gpr 11)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_20_RO_DBG_GPR_LOG_20_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_20_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_20_RO_DBG_GPR_LOG_20_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_20[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_20_RO_DBG_GPR_LOG_20_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_21 (0x890d0000 + 0x0258)---

    RO_DBG_GPR_LOG_21[31..0]     - (RO) DBG_GPR_LOG_21  (destination gpr 11)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_21_RO_DBG_GPR_LOG_21_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_21_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_21_RO_DBG_GPR_LOG_21_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_21[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_21_RO_DBG_GPR_LOG_21_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_22 (0x890d0000 + 0x025C)---

    RO_DBG_GPR_LOG_22[31..0]     - (RO) DBG_GPR_LOG_22 (source gpr 12)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_22_RO_DBG_GPR_LOG_22_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_22_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_22_RO_DBG_GPR_LOG_22_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_22[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_22_RO_DBG_GPR_LOG_22_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_23 (0x890d0000 + 0x0260)---

    RO_DBG_GPR_LOG_23[31..0]     - (RO) DBG_GPR_LOG_23  (destination gpr 12)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_23_RO_DBG_GPR_LOG_23_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_23_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_23_RO_DBG_GPR_LOG_23_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_23[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_23_RO_DBG_GPR_LOG_23_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_24 (0x890d0000 + 0x0264)---

    RO_DBG_GPR_LOG_24[31..0]     - (RO) DBG_GPR_LOG_24 (source gpr 13)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_24_RO_DBG_GPR_LOG_24_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_24_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_24_RO_DBG_GPR_LOG_24_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_24[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_24_RO_DBG_GPR_LOG_24_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_25 (0x890d0000 + 0x0268)---

    RO_DBG_GPR_LOG_25[31..0]     - (RO) DBG_GPR_LOG_25  (destination gpr 13)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_25_RO_DBG_GPR_LOG_25_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_25_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_25_RO_DBG_GPR_LOG_25_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_25[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_25_RO_DBG_GPR_LOG_25_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_26 (0x890d0000 + 0x026C)---

    RO_DBG_GPR_LOG_26[31..0]     - (RO) DBG_GPR_LOG_26 (source gpr 14)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_26_RO_DBG_GPR_LOG_26_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_26_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_26_RO_DBG_GPR_LOG_26_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_26[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_26_RO_DBG_GPR_LOG_26_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_27 (0x890d0000 + 0x0270)---

    RO_DBG_GPR_LOG_27[31..0]     - (RO) DBG_GPR_LOG_27  (destination gpr 14)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_27_RO_DBG_GPR_LOG_27_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_27_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_27_RO_DBG_GPR_LOG_27_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_27[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_27_RO_DBG_GPR_LOG_27_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_28 (0x890d0000 + 0x0274)---

    RO_DBG_GPR_LOG_28[31..0]     - (RO) DBG_GPR_LOG_28 (source gpr 15)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_28_RO_DBG_GPR_LOG_28_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_28_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_28_RO_DBG_GPR_LOG_28_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_28[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_28_RO_DBG_GPR_LOG_28_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_29 (0x890d0000 + 0x0278)---

    RO_DBG_GPR_LOG_29[31..0]     - (RO) DBG_GPR_LOG_29  (destination gpr 15)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_29_RO_DBG_GPR_LOG_29_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_29_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_29_RO_DBG_GPR_LOG_29_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_29[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_29_RO_DBG_GPR_LOG_29_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_30 (0x890d0000 + 0x027C)---

    RO_DBG_GPR_LOG_30[31..0]     - (RO) DBG_GPR_LOG_30 (source gpr 16)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_30_RO_DBG_GPR_LOG_30_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_30_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_30_RO_DBG_GPR_LOG_30_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_30[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_30_RO_DBG_GPR_LOG_30_SHFT 0

/* =====================================================================================

  ---DBG_GPR_LOG_31 (0x890d0000 + 0x0280)---

    RO_DBG_GPR_LOG_31[31..0]     - (RO) DBG_GPR_LOG_31  (destination gpr 16)

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_31_RO_DBG_GPR_LOG_31_ADDR CONN_MCU_EXCP_CON_DBG_GPR_LOG_31_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_31_RO_DBG_GPR_LOG_31_MASK 0xFFFFFFFF                // RO_DBG_GPR_LOG_31[31..0]
#define CONN_MCU_EXCP_CON_DBG_GPR_LOG_31_RO_DBG_GPR_LOG_31_SHFT 0

/* =====================================================================================

  ---DBG_PC_TRIG_CTL (0x890d0000 + 0x0300)---

    DBG_PC_TRIG_MODE[0]          - (RW) 1'b1: DBG_PC_TRIGGER MODE Enable
    DBG_PC_TRIG_VALUE[31..1]     - (RW) DBG_PC_TRIGGER MODE Address Setting

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_DBG_PC_TRIG_VALUE_ADDR CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_DBG_PC_TRIG_VALUE_MASK 0xFFFFFFFE                // DBG_PC_TRIG_VALUE[31..1]
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_DBG_PC_TRIG_VALUE_SHFT 1
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_DBG_PC_TRIG_MODE_ADDR CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_DBG_PC_TRIG_MODE_MASK 0x00000001                // DBG_PC_TRIG_MODE[0]
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_CTL_DBG_PC_TRIG_MODE_SHFT 0

/* =====================================================================================

  ---DBG_GPR_TRIG_CTL (0x890d0000 + 0x0304)---

    DBG_GPR_TRIG_MODE[0]         - (RW) 1'b1: DBG_GPR_TRIGGER MODE Enable
    DBG_GPR_TRIG_VALUE[31..1]    - (RW) DBG_GPR_TRIGGER MODE Address Setting

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_DBG_GPR_TRIG_VALUE_ADDR CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_DBG_GPR_TRIG_VALUE_MASK 0xFFFFFFFE                // DBG_GPR_TRIG_VALUE[31..1]
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_DBG_GPR_TRIG_VALUE_SHFT 1
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_DBG_GPR_TRIG_MODE_ADDR CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_DBG_GPR_TRIG_MODE_MASK 0x00000001                // DBG_GPR_TRIG_MODE[0]
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_CTL_DBG_GPR_TRIG_MODE_SHFT 0

/* =====================================================================================

  ---DBG_PC_TRIG_STOP_CTL (0x890d0000 + 0x0308)---

    DBG_PC_TRIG_STOP_MODE[0]     - (RW) 1'b1: DBG_PC_TRIGGER STOP MODE Enable
    DBG_PC_TRIG_STOP_VALUE[31..1] - (RW) DBG_PC_TRIGGER STOP MODE Address Setting

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_DBG_PC_TRIG_STOP_VALUE_ADDR CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_DBG_PC_TRIG_STOP_VALUE_MASK 0xFFFFFFFE                // DBG_PC_TRIG_STOP_VALUE[31..1]
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_DBG_PC_TRIG_STOP_VALUE_SHFT 1
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_DBG_PC_TRIG_STOP_MODE_ADDR CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_DBG_PC_TRIG_STOP_MODE_MASK 0x00000001                // DBG_PC_TRIG_STOP_MODE[0]
#define CONN_MCU_EXCP_CON_DBG_PC_TRIG_STOP_CTL_DBG_PC_TRIG_STOP_MODE_SHFT 0

/* =====================================================================================

  ---DBG_GPR_TRIG_STOP_CTL (0x890d0000 + 0x030C)---

    DBG_GPR_TRIG_STOP_MODE[0]    - (RW) 1'b1:DBG_GPR_TRIGGER STOP MODE Enable
    DBG_GPR_TRIG_STOP_VALUE[31..1] - (RW) DBG_GPR_TRIGGER STOP MODE Address Setting

 =====================================================================================*/
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_DBG_GPR_TRIG_STOP_VALUE_ADDR CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_DBG_GPR_TRIG_STOP_VALUE_MASK 0xFFFFFFFE                // DBG_GPR_TRIG_STOP_VALUE[31..1]
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_DBG_GPR_TRIG_STOP_VALUE_SHFT 1
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_DBG_GPR_TRIG_STOP_MODE_ADDR CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_ADDR
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_DBG_GPR_TRIG_STOP_MODE_MASK 0x00000001                // DBG_GPR_TRIG_STOP_MODE[0]
#define CONN_MCU_EXCP_CON_DBG_GPR_TRIG_STOP_CTL_DBG_GPR_TRIG_STOP_MODE_SHFT 0

#ifdef __cplusplus
}
#endif

#endif // __CONN_MCU_EXCP_CON_REGS_H__
