################################################################
# AP Common Feature Selection
################################################################
# Support Multiple Interface within single driver
CONFIG_MULTI_INF=y

#ifdef WDS_SUPPORT
# Support WDS function
CONFIG_WDS=y
#endif /* WDS_SUPPORT */

#ifdef DOT11_SAE_SUPPORT
CONFIG_WPA3_SUPPORT=y
#ifdef CONFIG_OWE_SUPPORT
# Support Enhanced Open (OWE)
CONFIG_OWE_SUPPORT=y
#endif /* CONFIG_OWE_SUPPORT */
#endif /* DOT11_SAE_SUPPORT */

#ifdef APCLI_SUPPORT
# Support AP-Client function
CONFIG_APCLI=y
#ifdef MWDS
# Support Mixed WDS
CONFIG_MWDS=n
#endif /* MWDS */
#ifdef ROAMING_ENHANCE_SUPPORT
# Roaming Enhance Support
CONFIG_ROAMING_ENHANCE_SUPPORT=n
#endif /* ROAMING_ENHANCE_SUPPORT */
#endif /* APCLI_SUPPORT */

#ifdef VOW_SUPPORT
CONFIG_VOW_SUPPORT=y
CONFIG_PKTLOSS_CHK=y
CONFIG_RED_SUPPORT=y
CONFIG_DABS_QOS=y
#endif /* VOW_SUPPORT */

#ifdef MT_DFS_SUPPORT
#Support DFS function
CONFIG_MT_DFS_SUPPORT=y
#endif /* MT_DFS_SUPPORT */

#ifdef DFS_ADJ_BW_ZERO_WAIT
#Support SW-based zero wait DFS function
CONFIG_DFS_ADJ_BW_ZERO_WAIT=y
#endif /* DFS_ADJ_BW_ZERO_WAIT */

#ifdef DFS_SDB_SUPPORT
#Support selectable dual band(use dedicateRX to monitor inband radar)
CONFIG_DFS_SDB_SUPPORT=y
#endif /* DFS_SDB_SUPPORT */

#Support IGMP-Snooping function.
CONFIG_IGMP_SNOOP_SUPPORT=y

#Support Background Scan function
CONFIG_BACKGROUND_SCAN_SUPPORT=n

#ifdef WEPAUTO_OPEN_FIRST
#Support WEPAUTO mode try Open first then shared
CONFIG_WEPAUTO_OPEN_FIRST_SUPPORT=y
#endif

#ifdef AIR_MONITOR
# Support Air Monitor
CONFIG_AIR_MONITOR=n
#endif /* AIR_MONITOR */

#Support GreenAP function
CONFIG_GREENAP_SUPPORT=y

#ifdef RSSI_FEEDBACK
CONFIG_RSSI_FEEDBACK=n
#endif /* RSSI_FEEDBACK */


#Support PCIE ASPM dynamic control
CONFIG_PCIE_ASPM_DYM_CTRL_SUPPORT=n

#Support for Auto channel select enhance
CONFIG_AUTO_CH_SELECT_ENHANCE=n

#Support USB_BULK_BUF_ALIGMENT
CONFIG_USB_BULK_BUF_ALIGMENT=n

#Support for EXT_CHANNEL
CONFIG_EXT_BUILD_CHANNEL_LIST=n

#Support for IDS
CONFIG_IDS_SUPPORT=y

#ifdef CONFIG_MULTI_CHANNEL
CONFIG_MULTI_CHANNEL=n
#endif /* CONFIG_MULTI_CHANNEL */

#ifdef CONFIG_HOTSPOT
ifeq ($(CONFIG_PASSPOINT_R2),y)
CONFIG_HOTSPOT_SUPPORT=y
else
CONFIG_HOTSPOT_SUPPORT=n
endif
#endif /* CONFIG_HOTSPOT */
#ifdef CONFIG_VLAN_GTK_SUPPORT
ifeq ($(CONFIG_VLAN_GTK_SUPPORT),y)
WFLAGS += -DCONFIG_VLAN_GTK_SUPPORT
WFLAGS += -DDYNAMIC_VLAN_SUPPORT
endif
#endif /* CONFIG_VLAN_GTK_SUPPORT */

#ifdef WNM_SUPPORT
CONFIG_WNM_SUPPORT?=n
#endif /* WNM_SUPPORT */

#ifdef MICROWAVE_OVEN_SUPPORT
CONFIG_MICROWAVE_OVEN_SUPPORT=n
#endif /* MICROWAVE_OVEN_SUPPORT */

#ifdef CONFIG_TR181_SUPPORT
##CONFIG_TR181_SUPPORT=n
#endif /* TR181_SUPPORT */

################################################################
# AP Customized Feature Selection
################################################################
# Support HOSTAPD function
CONFIG_HOSTAPD_SUPPORT=n

#DSCP PRI SUPPORT
CONFIG_DSCP_PRI_SUPPORT=y

#ifdef WH_EVENT_NOTIFIER
# Support whole home customized event notify
CONFIG_WH_EVENT_NOTIFIER=n
#endif /* WH_EVENT_NOTIFIER */

#Support Smart Carrier Sense function
CONFIG_SMART_CARRIER_SENSE_SUPPORT=y

#Support features of Link Test support.
CONFIG_LINK_TEST_SUPPORT=n

#Client support WDS function
CONFIG_CLIENT_WDS_SUPPORT=n

#ifdef CONFIG_SNIFFER_SUPPORT
CONFIG_SNIFFER_SUPPORT=n
#endif

#ifdef CONFIG_SNIFFER_RADIOTAP_SUPPOR
CONFIG_SNIFFER_RADIOTAP_SUPPORT=n
#endif

#ifdef CONFIG_WF_RESET_SUPPORT
CONFIG_WF_RESET_SUPPORT=n
#endif

#Support experimental feature (E.g. en/dequeue in diff CPU)
CONFIG_EXPERIMENTAL_FEATURES_SUPPORT=n

################################################################
# AP IOT Feature Selection
################################################################

#ifdef VHT_TXBF_2G_EPIGRAM_IE
# Support VHT TXBF 2G with BRCM STA
CONFIG_VHT_TXBF_2G_EPIGRAM_IE=n
#endif /* VHT_TXBF_2G_EPIGRAM_IE */

#ifdef ACK_CTS_TIMEOUT_SUPPORT
CONFIG_ACK_CTS_TIMEOUT_SUPPORT=n
#endif

#Support AMPDU CONFIG Feature
CONFIG_AMPDU_CONF_SUPPORT=n

################################################################
# AP Feature Compiler Flag
################################################################
WFLAGS += -DCONFIG_AP_SUPPORT -DMBSS_SUPPORT -DIAPP_SUPPORT -DDOT1X_SUPPORT -DAP_SCAN_SUPPORT -DSCAN_SUPPORT
WFLAGS += -DMCAST_RATE_SPECIFIC
WFLAGS += -DMAC_ADDR_ADJACENT_CHK

ifeq ($(CONFIG_MULTI_INF),y)
WFLAGS += -DMULTI_INF_SUPPORT
endif

#ifdef WSC_INCLUDED
ifeq ($(CONFIG_WSC_INCLUDED),y)
WFLAGS += -DWSC_AP_SUPPORT -DWSC_V2_SUPPORT -DWSC_INCLUDED -DWSC_SINGLE_TRIGGER
ifeq ($(CONFIG_WSC_LED),y)
WFLAGS += -DWSC_LED_SUPPORT
endif
ifeq ($(CONFIG_WSC_NFC),y)
WFLAGS += -DWSC_NFC_SUPPORT
endif
ifeq ($(CONFIG_APCLI),y)
WFLAGS += -DWSC_STA_SUPPORT
endif
ifeq ($(CONFIG_CON_WPS_SUPPORT), y)
WFLAGS += -DCON_WPS -DCON_WPS_AP_SAME_UUID
endif
endif
#endif /* WSC_INCLUDED */

#ifdef WDS_SUPPORT
ifeq ($(CONFIG_WDS),y)
WFLAGS += -DWDS_SUPPORT
endif
#endif /* WDS_SUPPORT */

#ifdef DOT11_SAE_SUPPORT
ifeq ($(CONFIG_WPA3_SUPPORT),y)
WFLAGS += -DDOT11_SAE_SUPPORT -DDOT11_SUITEB_SUPPORT -DDOT11W_PMF_SUPPORT -DDOT11_SAE_PWD_ID_SUPPORT
WFLAGS += -DDOT11_SAE_OPENSSL_BN
#ifdef CONFIG_OWE_SUPPORT
ifeq ($(CONFIG_OWE_SUPPORT),y)
WFLAGS += -DCONFIG_OWE_SUPPORT
endif
#endif /* CONFIG_OWE_SUPPORT */
endif
#endif /* DOT11_SAE_SUPPORT */

#ifdef APCLI_SUPPORT
ifeq ($(CONFIG_APCLI),y)
WFLAGS += -DAPCLI_SUPPORT -DMAT_SUPPORT -DMULTI_APCLI_SUPPORT -DSCAN_SUPPORT -DMTFWD
WFLAGS += -DAPCLI_AUTO_CONNECT_SUPPORT -DAPCLI_AUTO_BW_TMP
WFLAGS += -DCONFIG_APSTA_MIXED_SUPPORT -DETH_CONVERT_SUPPORT
WFLAGS += -DCONFIG_STA_SUPPORT -DCONFIG_APCLI_INF_NAME -DDHCP_UC_SUPPORT -DBT_APCLI_SUPPORT
#WFLAGS += -DACCOUNTING_SUPPORT
#ifdef DOT11_SAE_SUPPORT
ifeq ($(CONFIG_WPA3_SUPPORT),y)
WFLAGS += -DAPCLI_SAE_SUPPORT
endif
#endif /* DOT11_SAE_SUPPORT */
endif
#ifdef MWDS
ifeq ($(CONFIG_MWDS),y)
WFLAGS += -DMWDS -DROUTING_TAB_SUPPORT
endif
#endif /* MWDS*/
ifeq ($(CONFIG_MBSS_AS_WDS_AP_SUPPORT),y)
WFLAGS += -DMBSS_AS_WDS_AP_SUPPORT
WFLAGS += -DCLIENT_WDS
endif

ifeq ($(CONFIG_WDS_STA_SUPPORT),y)
WFLAGS += -DAPCLI_AS_WDS_STA_SUPPORT
endif
#ifdef ROAMING_ENHANCE_SUPPORT
ifeq ($(CONFIG_ROAMING_ENHANCE_SUPPORT),y)
WFLAGS += -DROAMING_ENHANCE_SUPPORT
endif
#endif /* ROAMING_ENHANCE_SUPPORT */
#endif /* APCLI_SUPPORT */

#ifdef VOW_SUPPORT
ifeq ($(CONFIG_VOW_SUPPORT),y)
WFLAGS += -DVOW_SUPPORT
endif
#endif /* VOW_SUPPORT */
ifeq ($(CONFIG_PKTLOSS_CHK), y)
WFLAGS += -DPKTLOSS_CHK
endif
ifeq ($(CONFIG_DABS_QOS), y)
WFLAGS += -DDABS_QOS
endif

ifeq ($(CONFIG_SNIFFER_RADIOTAP_SUPPORT),y)
WFLAGS += -DSNIFFER_RADIOTAP_SUPPORT
endif


ifeq ($(CONFIG_WF_RESET_SUPPORT),y)
WFLAGS += -DWF_RESET_SUPPORT
endif

#ifdef MT_DFS_SUPPORT
ifeq ($(CONFIG_MT_DFS_SUPPORT),y)
WFLAGS += -DMT_DFS_SUPPORT
ifeq ($(CONFIG_MT_BAND4_DFS_SUPPORT),y)
WFLAGS += -DMT_BAND4_DFS_SUPPORT
endif
ifeq ($(CONFIG_DFS_ADJ_BW_ZERO_WAIT),y)
WFLAGS += -DDFS_ADJ_BW_ZERO_WAIT
endif
ifeq ($(CONFIG_DFS_SDB_SUPPORT),y)
WFLAGS += -DDFS_SDB_SUPPORT
endif
endif
#endif /* MT_DFS_SUPPORT */

ifeq ($(CONFIG_IGMP_SNOOP_SUPPORT),y)
WFLAGS += -DIGMP_SNOOP_SUPPORT
endif

ifeq ($(CONFIG_WEPAUTO_OPEN_FIRST_SUPPORT),y)
WFLAGS += -DWEPAUTO_OPEN_FIRST
endif

#ifdef AIR_MONITOR
ifeq ($(CONFIG_AIR_MONITOR),y)
WFLAGS += -DAIR_MONITOR
endif
#endif /* AIR_MONITOR */

ifeq ($(CONFIG_GREENAP_SUPPORT),y)
WFLAGS += -DGREENAP_SUPPORT
endif

ifeq ($(CONFIG_DSCP_PRI_SUPPORT),y)
WFLAGS += -DDSCP_PRI_SUPPORT
endif

ifeq ($(CONFIG_HOSTAPD_SUPPORT),y)
WFLAGS += -DHOSTAPD_SUPPORT
endif

#ifdef RSSI_FEEDBACK
ifeq ($(CONFIG_RSSI_FEEDBACK),y)
WFLAGS += -DRSSI_FEEDBACK
endif
#endif /* RSSI_FEEDBACK */


#ifdef WH_EVENT_NOTIFIER
ifeq ($(CONFIG_WH_EVENT_NOTIFIER),y)
WFLAGS += -DWH_EVENT_NOTIFIER
endif
#endif /* WH_EVENT_NOTIFIER */

ifeq ($(CONFIG_PCIE_ASPM_DYM_CTRL_SUPPORT),y)
WFLAGS += -DPCIE_ASPM_DYM_CTRL_SUPPORT
endif

ifeq ($(CONFIG_AUTO_CH_SELECT_ENHANCE),y)
WFLAGS += -DAUTO_CH_SELECT_ENHANCE
endif

ifeq ($(CONFIG_USB_BULK_BUF_ALIGMENT),y)
WFLAGS += -DUSB_BULK_BUF_ALIGMENT
endif

ifeq ($(CONFIG_EXT_BUILD_CHANNEL_LIST),y)
WFLAGS += -DEXT_BUILD_CHANNEL_LIST
endif

ifeq ($(CONFIG_IDS_SUPPORT),y)
WFLAGS += -DIDS_SUPPORT
endif

#ifdef CONFIG_MULTI_CHANNEL
ifeq ($(CONFIG_MULTI_CHANNEL),y)
WFLAGS += -DCONFIG_MULTI_CHANNEL
endif
#endif /* CONFIG_MULTI_CHANNEL */

#ifdef CONFIG_HOTSPOT
ifeq ($(CONFIG_HOTSPOT_SUPPORT),y)
WFLAGS += -DCONFIG_DOT11U_INTERWORKING -DCONFIG_DOT11V_WNM -DCONFIG_HOTSPOT -DCONFIG_HOTSPOT_R2 -DCONFIG_HOTSPOT_R3
endif
#endif /* CONFIG_HOTSPOT */

#ifdef WNM_SUPPORT
ifeq ($(CONFIG_WNM_SUPPORT),y)
WFLAGS += -DCONFIG_DOT11V_WNM
endif
#endif /* WNM_SUPPORT */

#ifdef MICROWAVE_OVEN_SUPPORT
ifeq ($(CONFIG_MICROWAVE_OVEN_SUPPORT),y)
WFLAGS += -DMICROWAVE_OVEN_SUPPORT
endif
#endif /* MICROWAVE_OVEN_SUPPORT */

ifeq ($(CONFIG_SMART_CARRIER_SENSE_SUPPORT),y)
WFLAGS += -DSMART_CARRIER_SENSE_SUPPORT
endif

ifeq ($(CONFIG_LINK_TEST_SUPPORT),y)
WFLAGS += -DLINK_TEST_SUPPORT
endif

ifeq ($(CONFIG_CLIENT_WDS_SUPPORT),y)
WFLAGS += -DCLIENT_WDS
endif

ifeq ($(CONFIG_SEL_DUAL_BAND_SUPPORT),y)
WFLAGS += -DSEL_DUAL_BAND
endif


#ifdef VHT_TXBF_2G_EPIGRAM_IE
ifeq ($(CONFIG_TXBF_SUPPORT),y)
ifeq ($(CONFIG_VHT_TXBF_2G_EPIGRAM_IE),y)
WFLAGS += -DVHT_TXBF_2G_EPIGRAM_IE
endif
endif
#endif /* VHT_TXBF_2G_EPIGRAM_IE */

ifeq ($(CONFIG_BACKGROUND_SCAN_SUPPORT),y)
WFLAGS += -DBACKGROUND_SCAN_SUPPORT -DIPI_MAINRADIO_SCAN_SUPPORT
endif

ifeq ($(CONFIG_MAP_SUPPORT),y)
WFLAGS += -DA4_CONN -DROUTING_TAB_SUPPORT -DWAPP_SUPPORT -DCONFIG_MAP_SUPPORT
#WFLAGS += -DCFG80211_BYPASS
ifeq ($(CONFIG_MAP_HOSTAPD_SUPPORT),y)
WFLAGS += -DMTK_HOSTAPD_SUPPORT
WFLAGS += -DMTK_MLO_MAP_SUPPORT
endif
ifeq ($(CONFIG_MAP_VENDOR_SUPPORT),y)
WFLAGS += -DMAP_VENDOR_SUPPORT
endif
WFLAGS += -DMAP_MLO_UPLINK
ifeq ($(CONFIG_MAP_R6_SUPPORT),y)
WFLAGS += -DMAP_R6
endif
ifeq ($(CONFIG_MAP_R2_VER_SUPPORT),y)
WFLAGS += -DMAP_R2 -DMAP_TS_TRAFFIC_SUPPORT
endif
ifeq ($(CONFIG_MAP_R2_6E_SUPPORT), y)
WFLAGS += -DMAP_6E_SUPPORT
endif
ifeq ($(CONFIG_MTK_EM_PLUS_SUPPORT),y)
WFLAGS += -DEM_PLUS_SUPPORT
endif
ifeq ($(CONFIG_MAP_R3_6E_SUPPORT), y)
WFLAGS += -DMAP_R3_6E_SUPPORT
endif

ifeq ($(CONFIG_MAP_R3_VER_SUPPORT),y)
WFLAGS += -DCHANNEL_SWITCH_MONITOR_CONFIG -DDPP_SUPPORT -DDPP_R2_SUPPORT
WFLAGS += -DMAP_R3_WF6 -DMAP_R3
endif
ifeq ($(CONFIG_MAP_R4_VER_SUPPORT),y)
WFLAGS += -DMAP_R4
endif
ifeq ($(CONFIG_MAP_R5_VER_SUPPORT),y)
WFLAGS += -DMAP_R5
endif
endif

ifeq ($(CONFIG_AMPDU_CONF_SUPPORT),y)
WFLAGS += -DAMPDU_CONF_SUPPORT
endif

#ifdef ACK_CTS_TIMEOUT_SUPPORT
ifeq ($(CONFIG_ACK_CTS_TIMEOUT_SUPPORT),y)
WFLAGS += -DACK_CTS_TIMEOUT_SUPPORT
endif
#endif
ifeq ($(CONFIG_TR181_SUPPORT),y)
WFLAGS += -DTR181_SUPPORT
endif

ifeq ($(CONFIG_TXRX_STAT_SUPPORT),y)
WFLAGS += -DTXRX_STAT_SUPPORT
endif

ifeq ($(CONFIG_QOS_R1_SUPPORT), y)
    WFLAGS += -DQOS_R1 -DQOS_R2 -DQOS_R3 -DMSCS_PROPRIETARY -DDABS_QOS
    WFLAGS += -DEPCS_SUPPORT
endif

ifeq ($(CONFIG_DFS_SLAVE_SUPPORT),y)
WFLAGS += -DDFS_SLAVE_SUPPORT
endif
ifeq ($(CONFIG_ANDLINK_SUPPORT),y)
WFLAGS += -DANDLINK_FEATURE_SUPPORT -DANDLINK_HOSTNAME_IP  -DANDLINK_V4_0
endif

WFLAGS += -DMLR_SUPPORT
#support WIFI_COSR_SUPPORT
WFLAGS += -DWIFI_COSR_SUPPORT
