################################################################
# Chipset specific definitions - MT Series
#	Example:
# CONFIG_MT_RF=y
# CONFIG_MT_BBP=y
# CONFIG_MT_MAC=y
# CONFIG_MT_DMAC=n
# CONFIG_MT_FMAC=n
# CONFIG_MT_BMAC=n
# CONFIG_INF_PCI=y
# CONFIG_MAC_PCI=y
# CONFIG_INF_USB=n
# CONFIG_MAC_USB=n
# CONFIG_INF_RBUS=n
# CONFIG_CUT_THROUGH=y
# CONFIG_RX_CUT_THROUGH=n
# CONFIG_CUT_THROUGH_DBG=n
# CONFIG_NEED_ROM_PATCH=y
# CONFIG_FWOWN_SUPPORT=y
# CONFIG_MU_MIMO_SUPPORT=n
# CONFIG_FALCON_MURU_SUPPORT=y
# CONFIG_RX_SCATTER=n
# CONFIG_HDR_TRANS_TX_SUPPORT=y
# CONFIG_HDR_TRANS_RX_SUPPORT=y
# CONFIG_HW_TX_AMSDU_SUPPORT=n
# CONFIG_DOT11_VHT_SUPPORT=y
# CONFIG_DOT11_HE_SUPPORT=n
# CONFIG_RATE_ADAPT_AGBS_SUPPORT=y
# CONFIG_RACTRL_FW_OFFLOAD_SUPPORT=y
################################################################



#ifdef MT7990
ifneq ($(findstring mt7990,$(CHIPSET)),)
#------ Chip HW/SW definitions ------#
CONFIG_MT_RF=y
CONFIG_MT_BBP=y
CONFIG_MT_MAC=y
CONFIG_MT_FMAC=n
CONFIG_MT_BMAC=y
CONFIG_MT_DMAC=y
CONFIG_INF_PCI=y
CONFIG_MAC_PCI=y
CONFIG_CUT_THROUGH=y
CONFIG_NEED_ROM_PATCH=y
CONFIG_NEED_FW_HEADER=n
#CONFIG_FWOWN_SUPPORT=y
CONFIG_MU_MIMO_SUPPORT=n
#Todo: Have build error when MIMO enable
CONFIG_FALCON_MURU_SUPPORT=y
CONFIG_HDR_TRANS_TX_SUPPORT=y
CONFIG_HDR_TRANS_RX_SUPPORT=y
CONFIG_HW_TX_AMSDU_SUPPORT=y
CONFIG_DOT11_VHT_SUPPORT=y
CONFIG_DOT11_HE_SUPPORT=y
CONFIG_DOT11_EHT_SUPPORT=y
CONFIG_RATE_ADAPT_AGBS_SUPPORT=y
CONFIG_RACTRL_FW_OFFLOAD_SUPPORT=y
CONFIG_RX_SCATTER=y
CONFIG_CTXD_MEM_CPY=y
CONFIG_CTXD_SCATTER_AND_GATHER=n
CONFIG_RX_CUT_THROUGH=n
CONFIG_UNIFIED_COMMAND=y
CONFIG_VOW_SUPPORT=y
CONFIG_CAL_FREE_IC_SUPPORT=y
CONFIG_PRE_CAL_SUPPORT=y
CONFIG_SWACI_MECHANISM_SUPPORT=y

WFLAGS += -DSOFT_BIP_GMAC
WFLAGS += -DMT7990 -DA_BAND_SUPPORT
WFLAGS += -DMAC_INIT_OFFLOAD
WFLAGS += -DPKT_BUDGET_CTRL_SUPPORT
WFLAGS += -DSTA_LP_PHASE_2_SUPPORT -DCONFIG_PM_BIT_HW_MODE
WFLAGS += -DDBG_AMSDU
WFLAGS += -DDOT11V_MBSSID_SUPPORT -DPEAK_ENHANCE -DCFG_JUMBO_SUPPORT -DADJUST_TXOP_NEW_ARCH
WFLAGS += -DCONFIG_3_WIRE_SUPPORT
WFLAGS += -DCFG_WIFI_MT7990_BAND_NUM=3
ifeq ($(CONFIG_FPGA_MODE),y)
CONFIG_NEED_ROM_PATCH=n
WFLAGS += -DMT7990_FPGA
WFLAGS += -DCONFIG_FPGA_MODE
endif
ifeq ($(CONFIG_PRE_CAL_SUPPORT),y)
WFLAGS += -DPRE_CAL_MT7990_SUPPORT
endif
ifeq ($(CONFIG_IGMP_SNOOP_SUPPORT),y)
WFLAGS += -DIGMP_SNOOPING_NON_OFFLOAD -DIGMP_SNOOPING_DENY_LIST
endif
ifeq ($(CONFIG_CSI_SUPPORT),y)
WFLAGS += -DCFG_SUPPORT_CSI
endif
endif
#endif /* End of MT7990 */

#ifdef MT7992
ifneq ($(findstring mt7992,$(CHIPSET)),)
#------ Chip HW/SW definitions ------#
CONFIG_MT_RF=y
CONFIG_MT_BBP=y
CONFIG_MT_MAC=y
CONFIG_MT_FMAC=n
CONFIG_MT_BMAC=y
CONFIG_MT_DMAC=y
CONFIG_INF_PCI=y
CONFIG_MAC_PCI=y
CONFIG_CUT_THROUGH=y
CONFIG_NEED_ROM_PATCH=y
CONFIG_NEED_FW_HEADER=n
#CONFIG_FWOWN_SUPPORT=y
CONFIG_MU_MIMO_SUPPORT=n
#Todo: Have build error when MIMO enable
CONFIG_FALCON_MURU_SUPPORT=y
CONFIG_HDR_TRANS_TX_SUPPORT=y
CONFIG_HDR_TRANS_RX_SUPPORT=y
CONFIG_HW_TX_AMSDU_SUPPORT=y
CONFIG_DOT11_VHT_SUPPORT=y
CONFIG_DOT11_HE_SUPPORT=y
CONFIG_DOT11_EHT_SUPPORT=y
CONFIG_RATE_ADAPT_AGBS_SUPPORT=y
CONFIG_RACTRL_FW_OFFLOAD_SUPPORT=y
CONFIG_RX_SCATTER=y
CONFIG_CTXD_MEM_CPY=y
CONFIG_CTXD_SCATTER_AND_GATHER=n
CONFIG_RX_CUT_THROUGH=n
CONFIG_UNIFIED_COMMAND=y
CONFIG_VOW_SUPPORT=y
CONFIG_CAL_FREE_IC_SUPPORT=y
CONFIG_PRE_CAL_SUPPORT=y
CONFIG_RED_SUPPORT=y
CONFIG_SWACI_MECHANISM_SUPPORT=y

WFLAGS += -DSOFT_BIP_GMAC
WFLAGS += -DMT7992 -DA_BAND_SUPPORT
WFLAGS += -DMAC_INIT_OFFLOAD
WFLAGS += -DPKT_BUDGET_CTRL_SUPPORT
WFLAGS += -DSTA_LP_PHASE_2_SUPPORT -DCONFIG_PM_BIT_HW_MODE
WFLAGS += -DDBG_AMSDU
WFLAGS += -DDOT11V_MBSSID_SUPPORT -DPEAK_ENHANCE -DADJUST_TXOP_NEW_ARCH -DCFG_JUMBO_SUPPORT
WFLAGS += -DCONFIG_3_WIRE_SUPPORT
WFLAGS += -DCFG_WIFI_MT7992_BAND_NUM=2
WFLAGS += -DIBF_BITMAP_SUPPORT
ifeq ($(CONFIG_FPGA_MODE),y)
CONFIG_NEED_ROM_PATCH=n
WFLAGS += -DMT7992_FPGA
WFLAGS += -DCONFIG_FPGA_MODE
endif
ifeq ($(CONFIG_SKU_TYPE),BE3600SDB)
WFLAGS += -DMT7992_SKU_BE3600SDB
endif
ifeq ($(CONFIG_PRE_CAL_SUPPORT),y)
WFLAGS += -DPRE_CAL_MT7992_SUPPORT
endif
ifeq ($(CONFIG_IGMP_SNOOP_SUPPORT),y)
ifeq ($(CONFIG_CPE_SUPPORT),y)
WFLAGS += -DIGMP_SNOOPING_NON_OFFLOAD
else
WFLAGS += -DIGMP_SNOOPING_OFFLOAD
endif
endif
ifeq ($(CONFIG_CSI_SUPPORT),y)
WFLAGS += -DCFG_SUPPORT_CSI
endif
endif
#endif /* End of MT7992 */

#ifdef MT7993
ifneq ($(findstring mt7993,$(CHIPSET)),)
#------ Chip HW/SW definitions ------#
CONFIG_MT_RF=y
CONFIG_MT_BBP=y
CONFIG_MT_MAC=y
CONFIG_MT_FMAC=n
CONFIG_MT_BMAC=y
CONFIG_MT_DMAC=y
CONFIG_INF_PCI=y
CONFIG_MAC_PCI=y
CONFIG_CUT_THROUGH=y
CONFIG_NEED_ROM_PATCH=y
CONFIG_NEED_FW_HEADER=n
#CONFIG_FWOWN_SUPPORT=y
CONFIG_MU_MIMO_SUPPORT=n
#Todo: Have build error when MIMO enable
CONFIG_FALCON_MURU_SUPPORT=y
CONFIG_HDR_TRANS_TX_SUPPORT=y
CONFIG_HDR_TRANS_RX_SUPPORT=y
CONFIG_HW_TX_AMSDU_SUPPORT=y
CONFIG_DOT11_VHT_SUPPORT=y
CONFIG_DOT11_HE_SUPPORT=y
CONFIG_DOT11_EHT_SUPPORT=y
CONFIG_RATE_ADAPT_AGBS_SUPPORT=y
CONFIG_RACTRL_FW_OFFLOAD_SUPPORT=y
CONFIG_RX_SCATTER=y
CONFIG_CTXD_MEM_CPY=y
CONFIG_CTXD_SCATTER_AND_GATHER=n
CONFIG_RX_CUT_THROUGH=n
CONFIG_UNIFIED_COMMAND=y
CONFIG_VOW_SUPPORT=y
CONFIG_CAL_FREE_IC_SUPPORT=y
CONFIG_PRE_CAL_SUPPORT=y
CONFIG_RED_SUPPORT=y
CONFIG_SWACI_MECHANISM_SUPPORT=y
CONFIG_FPGA_MODE=y

WFLAGS += -DSOFT_BIP_GMAC
WFLAGS += -DMT7993 -DA_BAND_SUPPORT
WFLAGS += -DMAC_INIT_OFFLOAD
WFLAGS += -DPKT_BUDGET_CTRL_SUPPORT
WFLAGS += -DSTA_LP_PHASE_2_SUPPORT -DCONFIG_PM_BIT_HW_MODE
WFLAGS += -DDBG_AMSDU
WFLAGS += -DDOT11V_MBSSID_SUPPORT -DPEAK_ENHANCE -DADJUST_TXOP_NEW_ARCH -DCFG_JUMBO_SUPPORT
WFLAGS += -DCONFIG_3_WIRE_SUPPORT
WFLAGS += -DCFG_WIFI_MT7993_BAND_NUM=2
WFLAGS += -DIBF_BITMAP_SUPPORT
ifeq ($(CONFIG_FPGA_MODE),y)
CONFIG_NEED_ROM_PATCH=n
CONFIG_CAL_FREE_IC_SUPPORT=n
CONFIG_PRE_CAL_SUPPORT=n
#Todo: just for bring up
CONFIG_RED_SUPPORT=n
WFLAGS += -DMT7993_FPGA
WFLAGS += -DCONFIG_FPGA_MODE
endif
ifeq ($(CONFIG_PRE_CAL_SUPPORT),y)
WFLAGS += -DPRE_CAL_MT7993_SUPPORT
endif
ifeq ($(CONFIG_IGMP_SNOOP_SUPPORT),y)
WFLAGS += -DIGMP_SNOOPING_NON_OFFLOAD -DIGMP_SNOOPING_DENY_LIST
endif
ifeq ($(CONFIG_CSI_SUPPORT),y)
WFLAGS += -DCFG_SUPPORT_CSI
endif
endif
#endif /* End of MT7993 */

################################################################
# Chipset Compiler Flag
################################################################
#------ Chip Feature ------#
ifeq ($(CONFIG_MT_RF),y)
WFLAGS += -DMT_RF
endif
ifeq ($(CONFIG_MT_BBP),y)
WFLAGS += -DMT_BBP
endif
ifeq ($(CONFIG_MT_MAC),y)
WFLAGS += -DMT_MAC
endif
ifeq ($(CONFIG_MT_DMAC),y)
WFLAGS += -DMT_DMAC
endif
ifeq ($(CONFIG_MT_FMAC),y)
WFLAGS += -DMT_FMAC
endif
ifeq ($(CONFIG_MT_BMAC),y)
WFLAGS += -DMT_BMAC
endif
ifeq ($(CONFIG_INF_PCI),y)
WFLAGS += -DRTMP_PCI_SUPPORT
endif
ifeq ($(CONFIG_MAC_PCI),y)
WFLAGS += -DRTMP_MAC_PCI
endif
ifeq ($(CONFIG_INF_RBUS),y)
WFLAGS += -DRTMP_RBUS_SUPPORT
endif
ifeq ($(CONFIG_INF_USB),y)
WFLAGS += -DRTMP_USB_SUPPORT
endif
ifeq ($(CONFIG_MAC_USB),y)
WFLAGS += -DRTMP_MAC_USB
endif
ifeq ($(CONFIG_CUT_THROUGH),y)
WFLAGS += -DCUT_THROUGH -DCUT_THROGH_DBG
ifeq ($(CONFIG_CTXD_MEM_CPY),y)
WFLAGS += -DCTXD_MEM_CPY -DCONFIG_TX_DELAY
endif
ifeq ($(CONFIG_CTXD_SCATTER_AND_GATHER),y)
WFLAGS += -DCTXD_SCATTER_AND_GATHER -DCONFIG_TX_DELAY
endif
endif
ifeq ($(CONFIG_RX_CUT_THROUGH),y)
WFLAGS += -DRX_CUT_THROUGH
endif
ifeq ($(CONFIG_CUT_THROUGH_DBG),y)
WFLAGS += -DCUT_THROUGH_DBG
endif
ifeq ($(CONFIG_NEED_ROM_PATCH), y)
WFLAGS += -DNEED_ROM_PATCH
endif
ifeq ($(CONFIG_NEED_FW_HEADER), y)
WFLAGS += -DNEED_FW_HEADER
endif
ifeq ($(CONFIG_FWOWN_SUPPORT),y)
WFLAGS += -DCONFIG_FWOWN_SUPPORT
endif
ifeq ($(CONFIG_FALCON_MURU_SUPPORT),y)
WFLAGS += -DCFG_SUPPORT_FALCON_MURU
endif
ifeq ($(CONFIG_RX_SCATTER),y)
WFLAGS += -DRX_SCATTER
endif
ifeq ($(CONFIG_HDR_TRANS_TX_SUPPORT),y)
WFLAGS += -DHDR_TRANS_TX_SUPPORT
endif
ifeq ($(CONFIG_HDR_TRANS_RX_SUPPORT),y)
WFLAGS += -DHDR_TRANS_RX_SUPPORT
endif
ifeq ($(CONFIG_HW_TX_AMSDU_SUPPORT),y)
WFLAGS += -DHW_TX_AMSDU_SUPPORT
endif
ifeq ($(CONFIG_UNIFIED_COMMAND), y)
WFLAGS += -DWIFI_UNIFIED_COMMAND
endif
ifeq ($(CONFIG_VOW_SUPPORT), y)
WFLAGS += -DVOW_SUPPORT
endif
ifeq ($(CONFIG_HIGH_PRIO_QUEUE_SUPPORT),y)
WFLAGS += -DHIGH_PRIO_QUEUE_SUPPORT
endif
